config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
  resources :games do
    resources :levels do
      resources :highscores
    end
  end
  resources :levels do
    resources :highscores 
  end
  
  get ":id", to: "games#show"
  get ":game_id/:level_id", to: "levels#show"
  get ":game_id/levels/new", to: "levels#new"

  get ":game_id/:level_id/new", to: "highscores#new"
  get ":game_id/:level_id/Highscores", to: "highscores#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :levels, dependent: :destroy
end

app/models/highscore.rb
class Highscore < ApplicationRecord
  belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :game
  has_many :highscores, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
   # @levels = @game.levels
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      if((params[:id]).to_i.to_s == params[:id])
        @game = Game.find(params[:id])
      else
        @game = Game.find_by_name(params[:id])
      end

    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  before_action :set_highscore, only: %i[ show edit update destroy ]

  # GET /highscores or /highscores.json
  def index
    @highscores = Highscore.all
  end

  # GET /highscores/1 or /highscores/1.json
  def show
  end

  # GET /highscores/new
  def new
    @level = Level.find(params[:level_id])
    @highscore = @level.highscores.build
  end

  # GET /highscores/1/edit
  def edit
  end

  # POST /highscores or /highscores.json
  def create

    @highscore = Highscore.new(highscore_params)

    respond_to do |format|
      if @highscore.save
        format.html { redirect_to @highscore.level, notice: "Highscore was successfully created." }
        format.json { render :show, status: :created, location: @highscore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highscores/1 or /highscores/1.json
  def update
    respond_to do |format|
      if @highscore.update(highscore_params)
        format.html { redirect_to highscore_url(@highscore), notice: "Highscore was successfully updated." }
        format.json { render :show, status: :ok, location: @highscore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highscores/1 or /highscores/1.json
  def destroy
    @highscore.destroy

    respond_to do |format|
      format.html { redirect_to highscores_url, notice: "Highscore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highscore

      @highscore = Highscore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def highscore_params
      params.require(:highscore).permit(:name, :time, :score, :level_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_game_level, only: %i[    ]
  before_action :set_level, only: %i[ update show edit destroy ]
  
  # GET /levels or /levels.json
  def index
    @levels = Level.all
    
  end

  # GET /levels/1 or /levels/1.json
  def show
    @game = @level.game

  end

  # GET /levels/new
  def new
    if((params[:game_id]).to_i.to_s == params[:game_id])
      @game = Game.find_by_id(params[:game_id])
    else
      @game = Game.find_by_name(params[:game_id])
    end
    @level = @game.levels.build
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels or /levels.json
  def create
    @game = Game.find_by_id(params[:game_id])
    @level = @game.levels.new(level_params)
    print("fhek")
    respond_to do |format|
      if @level.save
        format.html { redirect_to @level.game, notice: "Level was successfully created." }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1 or /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to level_url(@level), notice: "Level was successfully updated." }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1 or /levels/1.json
  def destroy
    
    @level.destroy

    respond_to do |format|
      format.html { redirect_to @game, notice: "Level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      # first try finding level by id
      if(params[:id])
        if((params[:id]).to_i.to_s == params[:id])
          @level = Level.find(params[:id])         #if id is an integer
        else
          @level = Level.find_by_name(params[:id]) #if id is a name
        end
      else #else try finding level by level id
        if((params[:level_id]).to_i.to_s == params[:level_id])
          @level = Level.find(params[:level_id])         #if level id is integer
        else
          @level = Level.find_by_name(params[:level_id]) # if level id is name
        end
      end
      @game = @level.game
    end

    def set_game_level
      if((params[:level_id]).to_i.to_s == params[:level_id])
        @level = Level.find(params[:level_id])
      else
        @game = Game.find_by_name(params[:game_id])
        @level = @game.levels.find_by_name(params[:level_id])
      end
    end

    # Only allow a list of trusted parameters through.
    def level_params
      params.require(:level).permit(:name, :gamemode, :image_url, :game_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_integer?
        self.to_i.to_s == self
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :game_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gamemode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game.levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.gamemode %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New level', new_game_level_path(@game) %> |
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/highscores/_form.html.erb
<%= form_with model: [@level, @highscore] do |form| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>

      <ul>
      <% @highscore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :highscore_name %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :highscore_time %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :highscore_score %>
  </div>

  <div class="field">
    <%= form.label :level_id %>
    <%= form.text_field :level_id, id: :highscore_level_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/highscores/edit.html.erb
<h1>Editing Highscore</h1>

<%= render 'form', highscore: @highscore %>

<%= link_to 'Show', @highscore %> |
<%= link_to 'Back', highscores_path %>

app/views/highscores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Highscores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Score</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highscores.each do |highscore| %>
      <tr>
        <td><%= highscore.name %></td>
        <td><%= highscore.time %></td>
        <td><%= highscore.score %></td>
        <td><%= highscore.level %></td>
        <td><%= link_to 'Show', highscore %></td>
        <td><%= link_to 'Edit', edit_highscore_path(highscore) %></td>
        <td><%= link_to 'Destroy', highscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highscore', new_highscore_path %>

app/views/highscores/new.html.erb
<h1>New Highscore</h1>

<%= render 'form', highscore: @highscore %>

<%= link_to 'Back', @level %>

app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @highscore.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @highscore.time %>
</p>

<p>
  <strong>Score:</strong>
  <%= @highscore.score %>
</p>

<p>
  <strong>Level:</strong>
  <%= @highscore.level %>
</p>

<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

app/views/home/index.html.erb
<h1>Welcome to the thingy thing</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamesServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_with model: [@game, @level] do |form| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :level_name %>
  </div>

  <div class="field">
    <%= form.label :gamemode %>
    <%= form.text_field :gamemode, id: :level_gamemode %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :level_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gamemode</th>
      <th>Image url</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.gamemode %></td>
        <td><%= level.image_url %></td>
        <td><%= level.game.name %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level for <%= @game.name%></h1>

<%= render 'form' %>

<%= link_to 'Back', games_url(@game) %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Gamemode:</strong>
  <%= @level.gamemode %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @level.image_url %>
</p>

<p>
  <strong>Game:</strong>
  <%= @level.game.name %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @level.highscores.each do |highscore| %>
      <tr>
        <td><%= highscore.name %></td>
        <td><%= highscore.time %></td>
        <td><%= highscore.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>